title: <p align="center"> Divakar B </p>
logo: /assets/img/DIVAKAR_B.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://https://www.linkedin.com/in/divakar-b-aa882833//">LinkedIn</a> |
  <a href="https://github.com/divakar1983b">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with RamcoSystems on Neural Network modelling for Soft sensor prediction.
  Working in Honeywell for Advanced Process control and simulation domain for 7 years.
  <br>
  </p>



theme: jekyll-theme-minimal
